//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneDirectoryF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Schedule { get; set; }
        public string FieldActivity { get; set; }

        public string phoneNumber { get { return "+" + PhoneNumber; } set { phoneNumber = value; } }
    }
}
